### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chassain** [TheBodger/MMM-FeedProvider-RSS#1]
Hello,

i decide to check all modules :)..something is missing
![Capture d’écran de 2020-07-12 09-35-12](https://user-images.githubusercontent.com/32990929/87241429-48a69e80-c423-11ea-89a9-d335d86a2c70.png)

it will be a pleasure to work again with you
Best regards

**Comment by TheBodger** [comment]
Hi 

I have amended the RSS module.

can you 

cd MagicMirror/modules/MMM-FeedProvider-RSS
git pull

and rerun the mirror, this time you should see an error message in the logs showing you are missing the required oldestage field. if you then add a valid oldestage field to the config (examples in the readme) you should see somethin like this on the screen:

![image](https://user-images.githubusercontent.com/41484656/87295912-d8b91680-c4fd-11ea-9c4b-d04aecbf3fda.png)

**Comment by TheBodger** [comment]
or use this RSS feed for a french version of the news:

		{
			module: "MMM-FeedProvider-RSS",
			config: {
				text: "MMM-FeedProvider-RSS",
				id: "mmfp-rss",
				consumerids: ["MMFD1"],
				feeds: [
					{ feedname: 'france24', 
						feedtitle: 'FR24', 
						feedurl: 'https://www.france24.com/fr/rss', 
						oldestage: 'today' },
				],
				datarefreshinterval: 15000,
			}
		},


![image](https://user-images.githubusercontent.com/41484656/87296604-e9b65780-c4fe-11ea-8ab6-da3b0e46c092.png)

**Comment by chassain** [comment]
Hi,

better but something wrong with lestfeeddate

![Capture d’écran de 2020-07-13 13-22-48](https://user-images.githubusercontent.com/32990929/87299334-19b82780-c50c-11ea-8d08-25ffe218b3d3.png)

**Comment by chassain** [comment]
it's now ok..i haven't seen i need to configure feeddisplay..i saw the example.js and i have modified my config.js...Sorry about that !

**Comment by chassain** [comment]
Is it possible to have horizontal position in place of vertical ?..in bottom center for example

**Comment by TheBodger** [comment]
hi yes you can have the messages bottom centre like this: using the config like:

display: {
					articlimage: false,
					refreshtime: 10000,
					articlecount: 2,
					rotationstyle: 'scroll',
					modulewidth: "40vw",
					sourcenamelength: 20,
					textbelowimage: true,
					articleage: true,
					articledescription: true,
					wraparticles: true,
				},

![image](https://user-images.githubusercontent.com/41484656/87396258-7a963d00-c5aa-11ea-9e10-af655a5f295f.png)

**Comment by chassain** [comment]
Hi,

not like this..more slide information on the width (second information on the right,....)

information 1    information 2   information 3

**Comment by chassain** [comment]
i can do it different if i put MMFD1(news) on left..MMFD2 (sports) on center and MMFD3 (international) on the right position with parameters articlecount 1 and scroll 
:)

**Comment by TheBodger** [comment]
ok - i understand . 

that would be a better way to do it as you have full control over the positioning of each of the informations. 

Thanks
